# Generated by Django 3.2.25 on 2024-12-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0103_auto_20241109_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hasBadges',
            field=models.BooleanField(default=True, help_text='Disable if your event does not include attendee badges.', verbose_name='Produce attendee badge'),
        ),
        migrations.AddField(
            model_name='event',
            name='hasVolunteering',
            field=models.BooleanField(default=True, help_text='Disable if your event does not accept public volunteers requests.', verbose_name='Accept volunteers'),
        ),
        migrations.AddField(
            model_name='event',
            name='emailOptions',
            field=models.BooleanField(default=True, help_text='Disable to remove the post-con survey and newsletter checkboxes.', verbose_name='Email options'),
        ),
    ]
