# Generated by Django 3.2.25 on 2025-02-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0106_auto_20250121_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='multiAttendeeCarts',
            field=models.BooleanField(default=True, help_text='Disable if your event only supports single attendees per order.', verbose_name='Multiple attendees in cart'),
        ),
    ]
