# Generated by Django 3.2.25 on 2025-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0107_auto_20250216_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceleveloption',
            name='autoCheckFree',
            field=models.BooleanField(default=True, help_text="Disable to prevent the option from being autos-elected if it's free.", verbose_name='Auto-select free'),
        ),
        migrations.AddField(
            model_name='priceleveloption',
            name='displayFreeLabel',
            field=models.BooleanField(default=True, help_text='Disable if the "Free" label should not be shown.', verbose_name='Display free text'),
        ),
    ]
