# Generated by Django 3.2.25 on 2025-05-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0109_more_terminal_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sentWelcomeEmail',
            field=models.BooleanField(default=False, help_text='Whether or not the welcome email has been sent.', verbose_name='Welcome email sent'),
        ),
        migrations.AlterField(
            model_name='firebase',
            name='square_terminal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.squaredevice', verbose_name='Square Terminal'),
        ),
    ]
