# Generated by Django 3.2.25 on 2025-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0109_add_trigram_extensions_20241114_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceleveloption',
            name='quantity',
            field=models.IntegerField(null=True, default=None, help_text='Limits the amount that can be sold.', verbose_name='Quantity'),
        ),
    ]
