# Generated by Django 3.2.25 on 2025-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0110_auto_20250219_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='parentPhone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
