# Generated by Django 3.2.25 on 2025-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0110_auto_20250529_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cabinAssignment',
            field=models.CharField(default=None, help_text='Which cabin number the guest is in', max_length=4, null=True, verbose_name='Cabin assignment'),
        ),
        migrations.AddField(
            model_name='order',
            name='campsiteAssignment',
            field=models.CharField(default=None, help_text='Which campsite the guest is in', max_length=4, null=True, verbose_name='Campsite assignment'),
        ),
    ]
