# Generated by Django 3.2.25 on 2025-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0111_auto_20250530_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attendingDinner',
            field=models.BooleanField(default=None, help_text='Whether or not the guests are attending dinner.', null=True, verbose_name='Attending dinner'),
        ),
    ]
