# Generated by Django 3.2.25 on 2025-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0111_auto_20250224_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevel',
            name='isVendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionExtraType',
            field=models.CharField(blank=True, choices=[('int', 'Quantity'), ('bool', 'Yes/No'), ('ShirtSizes', 'Shirt Size'), ('string', 'String')], max_length=100),
        ),
    ]
