# Generated by Django 3.2.25 on 2026-05-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0112_auto_20250531_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnsiteBadgeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='registration.order')),
            ],
            options={
                'unique_together': {('order', 'badge_number')},
            },
        ),
    ]
