# Generated by Django 3.2.25 on 2025-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0112_auto_20250305_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevel',
            name='minimumOrgDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
