# Generated by Django 3.2.25 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0113_auto_20250308_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='waiveRequiredDonation',
            field=models.BooleanField(default=False),
        ),
    ]
