# Generated by Django 3.2.25 on 2026-05-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0113_onsitebadgeassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitebadgeassignment',
            name='badge_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='onsitebadgeassignment',
            unique_together=set(),
        ),
    ]
