# Generated by Django 3.2.25 on 2025-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0114_auto_20250310_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkedInDate',
            field=models.DateTimeField(default=None, help_text='The time in which the guest was checked in to the event.', null=True, verbose_name='Checked In Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='wristBandCountPickedUp',
            field=models.IntegerField(default=None, help_text='The amount of wrist bands that were picked up from this order.', null=True, verbose_name='Wrist bands picked up'),
        ),
    ]
