# Generated by Django 3.2.25 on 2025-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0115_auto_20250527_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrcodeHash',
            field=models.CharField(default=None, help_text='Hashed secret within the emailed QR code.', max_length=200, null=True, verbose_name='QR code secret hash'),
        ),
    ]
