# Generated by Django 5.2.14 on 2026-05-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0119_update_pricelevels'),
        ('registration', '0114_onsitebadgeassignment_unique_badge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dealerEmail',
            field=models.CharField(blank=True, default='no-reply@sirencon.com', help_text='Email to display on error messages for dealer registration', max_length=200, verbose_name='Dealer Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrationEmail',
            field=models.CharField(blank=True, default='no-reply@sirencon.com', help_text='Email to display on error messages for attendee registration', max_length=200, verbose_name='Registration Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staffEmail',
            field=models.CharField(blank=True, default='no-reply@sirencon.com', help_text='Email to display on error messages for staff registration', max_length=200, verbose_name='Staff Email'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='registration.order')),
            ],
        ),
    ]
