# Generated by Django 5.2.14 on 2026-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0120_add_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiverPdfUrl',
            field=models.CharField(blank=True, help_text='URL to the signed waiver PDF stored in S3. Presence indicates waiver has been signed.', max_length=500, null=True, verbose_name='Waiver PDF URL'),
        ),
    ]
