name: Deploy to SirenCon Kubernetes Cluster

on:
  push:
    branches:
      - deploy/prod

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_TRIGGER_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_TRIGGER_SSH_PRIVATE_KEY }}

      - name: Invoke deployment workflow
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          DEPLOY_REVISION=$(git rev-parse --short HEAD)
          DEPLOY_ENVIRONMENT=${BRANCH#deploy/}

          gh workflow run deploy.yml \
            --repo fm-apis-deployment \
            --ref main \
            --field deploy_revision=$DEPLOY_REVISION \
            --field deploy_environment=$DEPLOY_ENVIRONMENT
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
